[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-ping",
  "allow-play",
  "allow-pause",
  "allow-pause-after",
  "allow-resume",
  "allow-stop",
  "allow-next",
  "allow-previous",
  "allow-seek",
  "allow-seek-and-play",
  "allow-get-state",
  "allow-start-service",
  "allow-stop-service",
  "allow-set-volume",
  "allow-set-normalization-config",
  "allow-set-server",
  "allow-set-playing-queue",
  "allow-get-playback-session",
  "allow-clear-playing-queue",
  "allow-set-play-mode",
  "allow-register-listener",
  "allow-remove-listener"
]
